version: '3.7'

services:
# mme is now going to be host only

  epc:
    image: wsrg/o5gs
    build:
      context: .
      args:
        arch: ${TAG-amd64}

  mme:
    depends_on:
      - hss
    image: wsrg/o5gs
    network_mode: "host"
    # networks:
      # dnet:
        # aliases:
          # - mme.localdomain
      # frontend:
    cap_add:
      - NET_ADMIN
      
    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/open5gs"
      NEPC_MME_NETNAME_SHORT: dnet
      NEPC_MME_NETNAME: dnet
      NEPC_MME_S1AP_ADDR: ${INTERFACE_IP}
      NEPC_MME_GTPC_ADDR: ${INTERFACE_IP}
      NEPC_SGW_GTPC_ADDR: sgw.localdomain
      NEPC_PGW_GTPC_ADDR: pgw.localdomain
      NEPC_MME_SGW_TLADDR: ${EXT_IP_EPC}    # this is the reachable IP of the EPC
      # NEPC_MME_ENB_TLADDR: ${EXT_IP_ENB}    # this is the external IP of the ENB
    command: /bin/bash -c "/usr/bin/open5gs-mmed -c /etc/open5gs/mme.yaml"
    # command: /bin/bash

    volumes:
      - ./freeDiameter:/etc/freeDiameter
      - ./confs/mme.yaml:/etc/open5gs/mme.yaml
      - ./loggy:/var/log/open5gs
    extra_hosts:
      - "hss.localdomain:172.22.11.2"
      - "sgw.localdomain:172.22.11.3"
      - "pcrf.localdomain:172.22.11.4"
      - "pgw.localdomain:172.22.11.5"

#hss is on br-dnet
  hss:
    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/open5gs"
      MONGOC_DISABLE_SHM: 1
    image: wsrg/o5gs
    # network_mode: "dnet"
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - hss.localdomain
        ipv4_address: 172.22.11.2
    command: /bin/bash -c "/usr/bin/open5gs-hssd -c /etc/open5gs/hss.yaml"
    # command: /bin/bash

    volumes:
      - ./freeDiameter:/etc/freeDiameter
      - ./confs/hss.yaml:/etc/open5gs/hss.yaml
      - ./loggy:/var/log/open5gs
    extra_hosts:
      - "mme.localdomain:${INTERFACE_IP}"

#sgw is on br-dnet
  sgw:
    image: wsrg/o5gs
    networks:
      default:
        aliases:
          - sgw.localdomain
        ipv4_address: 172.22.11.3
    # expose GTP-U port
    ports:
      - "2152:2152/udp"
    command: /bin/bash -c "/usr/bin/open5gs-sgwd -c /etc/open5gs/sgw.yaml"
    # command: /bin/bash

    environment:
      NEPC_SGW_GTPC_ADDR: 172.22.11.3
      NEPC_SGW_GTPU_ADDR: 172.22.11.3
      NEPC_FD_CLIENT_SRC_ADDR: ${INTERFACE_IP}
      MONGOC_DISABLE_SHM: 1
    volumes:
      - ./freeDiameter:/etc/freeDiameter
      - ./confs/sgw.yaml:/etc/open5gs/sgw.yaml
      - ./loggy:/var/log/open5gs
    extra_hosts:
      - "mme.localdomain:${INTERFACE_IP}"

#pcrf is on br-dnet
  pcrf:
    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/open5gs"
      MONGOC_DISABLE_SHM: 1

    image: wsrg/o5gs
    networks:
      default:
        aliases:
          - pcrf.localdomain
        ipv4_address: 172.22.11.4
    command: /bin/bash -c "/usr/bin/open5gs-pcrfd -c /etc/open5gs/pcrf.yaml"
    # command: /bin/bash

    volumes:
      - ./freeDiameter:/etc/freeDiameter
      - ./confs/pcrf.yaml:/etc/open5gs/pcrf.yaml
      - ./loggy:/var/log/open5gs
    extra_hosts:
      - "mme.localdomain:${INTERFACE_IP}"


#pgw is on br-dnet
  pgw:
    depends_on:
      - pcrf
    image: wsrg/o5gs
    # network_mode: "host"
    environment:
      NEPC_PGW_DNS4: ${DC_UE_DNS}
      NEPC_PGW_IP4: 192.168.215.1
      NEPC_PGW_MASK4: 24
      NEPC_PGW_IP6: ca09::1
      NEPC_PGW_MASK6: 64
      MONGOC_DISABLE_SHM: 1
      NEPC_PGW_GTPC_ADDR: 172.22.11.5
      NEPC_PGW_GTPU_ADDR: 172.22.11.5
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - pgw.localdomain
        ipv4_address: 172.22.11.5
    command: /bin/bash -c "env; /root/settun.sh; ip a; /usr/bin/open5gs-pgwd -c /etc/open5gs/pgw.yaml"
    # command: /bin/bash

    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./freeDiameter:/etc/freeDiameter
      - ./confs/pgw.yaml:/etc/open5gs/pgw.yaml
      - ./loggy:/var/log/open5gs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
    extra_hosts:
      - "mme.localdomain:${INTERFACE_IP}"

networks:
  default:
    name: dnet
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-dnet
    ipam:
      config:
      - subnet: 172.22.11.0/24
