version: '3'

services:
  test:
    image: wsrg/${DIST-ubuntu}-${TAG-bionic}-nextepc-build
    depends_on:
      - build
    environment:
      DB_URI: mongodb://mongodb/nextepc
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: nextepc-test
    command: /bin/bash -c "/root/setup.sh; /usr/bin/testcore"
