version: '3'

services:
  run:
    network_mode: "host"
    image: wsrg/${DIST-ubuntu}-${TAG-bionic}-nextepc-build
    depends_on:
      - build
    cap_add:
      - NET_ADMIN
    environment:
      DB_URI: consul://10.10.10.67:8500/nextepc
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    # volumes:
      # - config:/etc/nextepc
    hostname: nextepc-run
    command: /bin/bash -c "/root/setup.sh; /usr/bin/nextepc-epcd"
    # command: /bin/bash

# volumes:
  # config: {}
