version: '3'

services:
  dnet:
    build:
      context: ./build-dnet
    image: wsrg/nextepc-dnet:${TAG-amd64}
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      DB_URI: "consul://10.10.10.67:8500/nextepc"
      NEPC_PGW_DNS4: 10.10.10.67
      NEPC_PGW_IP4: 172.28.0.1
      NEPC_PGW_MASK4: 24
      NEPC_PGW_IP6: ca09::1
      NEPC_PGW_MASK6: 64
      NEPC_MME_NETNAME_SHORT: dnet
      NEPC_MME_NETNAME: dnet
      NEPC_MME_S1AP_ADDR: 192.168.44.10
      NEPC_MME_GTPC_ADDR: 127.0.0.2
      NEPC_SGW_GTPC_ADDR: 127.0.0.6
      NEPC_SGW_GTPU_ADDR: 192.168.44.10
      NEPC_PGW_GTPC_ADDR: 127.0.0.3
      NEPC_PGW_GTPU_ADDR: 127.0.0.3
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: nextepc-run
    command: /bin/bash -c "/root/settun.sh; /usr/bin/nextepc-epcd"
#    command: /bin/bash -c "echo 'dnet base' services"
    # command: /bin/bash

  mme:
    depends_on:
      - dnet
    image: wsrg/nextepc-dnet
    command: /bin/bash -c "/usr/bin/nextepc-mmed"

  base:
    build:
      context: ./${DIST-ubuntu}/${TAG-bionic}/base
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-bionic}
    image: wsrg/${DIST-ubuntu}-${TAG-bionic}-nextepc-base
    command: /bin/bash -c "echo 'base' services"

  build:
    build:
      context: ./build
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-bionic}
        username: wsrg
    image: wsrg/${DIST-ubuntu}-${TAG-bionic}-nextepc-build
    depends_on:
      - base
    command: /bin/bash -c "echo 'build' services"

  dev:
    build:
      context: ./${DIST-ubuntu}/${TAG-bionic}/dev
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-bionic}
        username: wsrg
    image: wsrg/${DIST-ubuntu}-${TAG-bionic}-nextepc-dev
    depends_on:
      - base
    environment:
      - DB_URI=mongodb://mongodb/nextepc
      - DISPLAY=$DISPLAY
    # - DISPLAY=docker.for.mac.localhost:0
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    # volumes:
      # - home:/home/wsrg
      # - ${HOME}:/mnt
      # - /tmp/.X11-unix:/tmp/.X11-unix
    # - /etc/localtime:/etc/localtime:ro
    # - /usr/share/zoneinfo/Europe/Helsinki:/etc/localtime:ro
    hostname: nextepc-dev
    user: wsrg
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
        /bin/bash -c "
            sudo chmod 666 /dev/net/tun
            sudo /root/setup.sh
            /bin/bash || exit 0
        "
# volumes:
  # mongodb: {}
  # home: {}
