version: '3.7'

services:
# mme is now going to be host only
  mme:
    depends_on:
      - hss
    image: wsrg/nextepc-dnet:${TAG-amd64}
    network_mode: "host"
    # networks:
      # dnet:
        # aliases:
          # - mme.localdomain
      # frontend:

    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/nextepc"
      NEPC_MME_NETNAME_SHORT: dnet
      NEPC_MME_NETNAME: dnet
      NEPC_MME_S1AP_ADDR: 192.168.44.10
      NEPC_MME_GTPC_ADDR: 172.22.11.1
      NEPC_SGW_GTPC_ADDR: sgw.localdomain
      NEPC_PGW_GTPC_ADDR: pgw.localdomain
      NEPC_MME_SGW_TLADDR: 192.168.44.10
      # NEPC_MME_ENB_TLADDR: 1.1.1.1
    command: /bin/bash -c "/usr/bin/nextepc-mmed -f /etc/nextepc/mme.conf"
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
      - ./confs/mme.conf:/etc/nextepc/mme.conf
      - ./loggy:/var/log/nextepc
    extra_hosts:
      - "hss.localdomain:172.22.11.2"
      - "sgw.localdomain:172.22.11.3"
      - "pcrf.localdomain:172.22.11.4"
      - "pgw.localdomain:172.22.11.5"

#hss is on br-dnet
  hss:
    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/nextepc"
    image: wsrg/nextepc-dnet:${TAG-amd64}
    # network_mode: "dnet"
    networks:
      default:
        aliases:
          - hss.localdomain
        ipv4_address: 172.22.11.2
    command: /bin/bash -c "/usr/bin/nextepc-hssd -f /etc/nextepc/hss.conf"
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
      - ./confs/hss.conf:/etc/nextepc/hss.conf
      - ./loggy:/var/log/nextepc
    extra_hosts:
      - "mme.localdomain:172.22.11.1"

#sgw is on br-dnet
  sgw:
    image: wsrg/nextepc-dnet:${TAG-amd64}
    networks:
      default:
        aliases:
          - sgw.localdomain
        ipv4_address: 172.22.11.3
    # expose GTP-U port
    ports:
      - "2152:2152/udp"
    command: /bin/bash -c "/usr/bin/nextepc-sgwd -f /etc/nextepc/sgw.conf"
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
      - ./confs/sgw.conf:/etc/nextepc/sgw.conf
      - ./loggy:/var/log/nextepc
    extra_hosts:
      - "mme.localdomain:172.22.11.1"

#pcrf is on br-dnet
  pcrf:
    environment:
      DB_URI: "consul://${DC_CONSUL_IP}:8500/nextepc"
    image: wsrg/nextepc-dnet:${TAG-amd64}
    networks:
      default:
        aliases:
          - pcrf.localdomain
        ipv4_address: 172.22.11.4
    command: /bin/bash -c "/usr/bin/nextepc-pcrfd -f /etc/nextepc/pcrf.conf"
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
      - ./confs/pcrf.conf:/etc/nextepc/pcrf.conf
      - ./loggy:/var/log/nextepc
    extra_hosts:
      - "mme.localdomain:172.22.11.1"


#pgw is on br-dnet
  pgw:
    depends_on:
      - pcrf
    image: wsrg/nextepc-dnet:${TAG-amd64}
    # network_mode: "host"
    environment:
      NEPC_PGW_DNS4: ${DC_UE_DNS}
      NEPC_PGW_IP4: 192.168.215.1
      NEPC_PGW_MASK4: 24
      NEPC_PGW_IP6: ca09::1
      NEPC_PGW_MASK6: 64
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - pgw.localdomain
        ipv4_address: 172.22.11.5
    command: /bin/bash -c "env; /root/settun.sh; ip a; /usr/bin/nextepc-pgwd -f /etc/nextepc/pgw.conf"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./freeDiameter:/etc/nextepc/freeDiameter
      - ./confs/pgw.conf:/etc/nextepc/pgw.conf
      - ./loggy:/var/log/nextepc
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
    extra_hosts:
      - "mme.localdomain:172.22.11.1"

networks:
  default:
    name: dnet
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-dnet
    ipam:
      config:
      - subnet: 172.22.11.0/24
